name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ktlint
        run: |
          ./ktlint "**/src/**/*.kt" --color --relative

      - name: Test
        run: ./gradlew test :sample-app:lintDebug :sample-app:assembleDebug
